version: '3.9'
services:
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db_files:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}

  cloud:
    image: nextcloud:fpm
    container_name: cloud
    restart: unless-stopped
    volumes:
      - ./cloud/data:/var/www/html/data
      - ./cloud/config:/var/www/html/config
      - nextcloud:/var/www/html
      - cloud-conf-connect:/usr/local/etc
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAINS}
      - NEXTCLOUD_DATA_DIR=${CLOUD_DATA_DIR}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_HOST=db
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./config/nginx:/etc/nginx/conf.d:ro
      - nextcloud:/var/www/html:ro
      - cloud-conf-connect:/var/connect:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - cloud

volumes:
  nextcloud:
  cloud-conf-connect:
